-- ==============================================================================
-- SkateCore: Admin Panel & Telemetry Infrastructure
-- ==============================================================================

-- 1. Create Telemetry Buffer Tables (Short retention)
CREATE TABLE IF NOT EXISTS public.telemetry_sessions (
    session_id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id UUID REFERENCES public.users(id) ON DELETE SET NULL,
    access_code_id UUID,
    device_type TEXT,
    operating_system TEXT,
    browser TEXT,
    browser_version TEXT,
    screen_size TEXT,
    orientation TEXT,
    timezone TEXT,
    app_version TEXT,
    login_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    logout_at TIMESTAMP WITH TIME ZONE,
    last_activity_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    session_duration_seconds INT DEFAULT 0
);

CREATE TABLE IF NOT EXISTS public.telemetry_events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id UUID REFERENCES public.telemetry_sessions(session_id) ON DELETE CASCADE,
    user_id UUID,
    event_type TEXT NOT NULL,
    payload JSONB DEFAULT '{}'::jsonb,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.telemetry_errors (
    error_id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    session_id UUID REFERENCES public.telemetry_sessions(session_id) ON DELETE CASCADE,
    user_id UUID,
    error_type TEXT,
    error_message TEXT,
    app_version TEXT,
    context JSONB DEFAULT '{}'::jsonb,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Enable RLS for telemetry
ALTER TABLE public.telemetry_sessions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.telemetry_events ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.telemetry_errors ENABLE ROW LEVEL SECURITY;

-- Allow inserts from authenticated users (or anon if we allow before login)
DROP POLICY IF EXISTS "Allow anon inserts to sessions" ON public.telemetry_sessions;
CREATE POLICY "Allow anon inserts to sessions" ON public.telemetry_sessions FOR INSERT WITH CHECK (true);

DROP POLICY IF EXISTS "Allow anon updates to own sessions" ON public.telemetry_sessions;
CREATE POLICY "Allow anon updates to own sessions" ON public.telemetry_sessions FOR UPDATE USING (true);

DROP POLICY IF EXISTS "Allow anon inserts to events" ON public.telemetry_events;
CREATE POLICY "Allow anon inserts to events" ON public.telemetry_events FOR INSERT WITH CHECK (true);

DROP POLICY IF EXISTS "Allow anon inserts to errors" ON public.telemetry_errors;
CREATE POLICY "Allow anon inserts to errors" ON public.telemetry_errors FOR INSERT WITH CHECK (true);

-- 2. Storage Bucket for Reports
INSERT INTO storage.buckets (id, name, public) VALUES ('skatecore_reports', 'skatecore_reports', false) ON CONFLICT (id) DO NOTHING;

-- Storage policies (Admin only)
DROP POLICY IF EXISTS "Admins can manage reports" ON storage.objects;
CREATE POLICY "Admins can manage reports" ON storage.objects FOR ALL USING (
  bucket_id = 'skatecore_reports' 
  AND EXISTS (
    SELECT 1 FROM public.users u WHERE u.id = auth.uid() AND (u.role = 'superadmin' OR u.email IN ('recursosparaministerios@gmail.com', 'contacto@alsiztech.com'))
  )
);

-- 3. Admin: Generate Access Code
CREATE OR REPLACE FUNCTION public.admin_generate_access_code(
  p_admin_email TEXT,
  p_duration_days INT,
  p_assigned_email TEXT DEFAULT NULL,
  p_type TEXT DEFAULT 'TESTER'
)
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, extensions
AS $$
DECLARE
  v_email    TEXT := LOWER(TRIM(p_admin_email));
  v_is_admin BOOLEAN;
  v_new_code TEXT;
  v_plan     TEXT;
BEGIN
  -- Verificar admin
  v_is_admin := v_email IN (
      'recursosparaministerios@gmail.com',
      'andradesanchezavril@gmail.com',
      'karenprofet@gmail.com',
      'contacto@alsiztech.com',
      'contactoalsiztech.com',
      'mauriandrade2@gmail.com'
    )
    OR EXISTS (
      SELECT 1 FROM public.users u
      WHERE LOWER(u.email) = v_email AND u.role = 'superadmin'
    );

  IF NOT v_is_admin THEN
    RETURN jsonb_build_object('success', false, 'error', 'No autorizado.');
  END IF;

  IF p_duration_days < 1 THEN
    RETURN jsonb_build_object('success', false, 'error', 'La duración debe ser mayor a 0.');
  END IF;

  -- Generar máscara única: SKC-[4 chars]-[4 chars]-[4 chars]
  v_new_code := 'SKC-' || 
                upper(substring(md5(random()::text) from 1 for 4)) || '-' ||
                upper(substring(md5(random()::text) from 5 for 4)) || '-' ||
                upper(substring(md5(random()::text) from 9 for 4));
                
  v_plan := CASE WHEN UPPER(p_type) = 'TESTER' THEN 'beta_tester' ELSE 'individual' END;

  INSERT INTO public.activation_codes
    (code, campaign, kind, duration_days, max_uses, used_count, status, subscription_plan, notes, expires_at)
  VALUES
    (v_new_code, 'ADMIN_GENERATED', 'GIFT', p_duration_days, 1, 0, 'AVAILABLE', v_plan, 
     'Generado por admin. Tipo: ' || p_type || '. Asignado a: ' || COALESCE(p_assigned_email, 'Ninguno'), 
     NOW() + INTERVAL '1 year'); -- Expira el CÓDIGO en 1 año si no se usa

  RETURN jsonb_build_object(
    'success', true, 
    'code', jsonb_build_object(
      'code', v_new_code,
      'duration_days', p_duration_days,
      'status', 'AVAILABLE',
      'assigned_email', p_assigned_email,
      'type', p_type,
      'created_at', NOW()
    )
  );
END;
$$;

-- 4. Admin: Revoke Code
CREATE OR REPLACE FUNCTION public.admin_revoke_access_code(
  p_admin_email TEXT,
  p_code TEXT
)
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, extensions
AS $$
DECLARE
  v_email    TEXT := LOWER(TRIM(p_admin_email));
  v_is_admin BOOLEAN;
BEGIN
  v_is_admin := v_email IN (
      'recursosparaministerios@gmail.com', 'contacto@alsiztech.com', 'contactoalsiztech.com'
    ) OR EXISTS (SELECT 1 FROM public.users u WHERE LOWER(u.email) = v_email AND u.role = 'superadmin');

  IF NOT v_is_admin THEN RETURN jsonb_build_object('success', false, 'error', 'No autorizado.'); END IF;

  UPDATE public.activation_codes
  SET status = 'REVOKED', notes = notes || ' | Revocado por admin el ' || NOW()
  WHERE code = p_code;

  RETURN jsonb_build_object('success', true);
END;
$$;

-- 5. Admin: Dashboard Stats
CREATE OR REPLACE FUNCTION public.admin_get_dashboard_stats(p_admin_email TEXT)
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, extensions
AS $$
DECLARE
  v_email    TEXT := LOWER(TRIM(p_admin_email));
  v_is_admin BOOLEAN;
  v_total_users INT;
  v_active_testers INT;
  v_active_codes INT;
  v_pending_codes INT;
  v_recent_sessions INT;
  v_recent_errors INT;
BEGIN
  v_is_admin := v_email IN (
      'recursosparaministerios@gmail.com', 'contacto@alsiztech.com', 'contactoalsiztech.com'
    ) OR EXISTS (SELECT 1 FROM public.users u WHERE LOWER(u.email) = v_email AND u.role = 'superadmin');
  IF NOT v_is_admin THEN RETURN jsonb_build_object('success', false, 'error', 'No autorizado.'); END IF;

  SELECT COUNT(*) INTO v_total_users FROM public.users;
  SELECT COUNT(*) INTO v_active_testers FROM public.users WHERE subscription_plan = 'beta_tester' AND access_expires_at > NOW();
  SELECT COUNT(*) INTO v_active_codes FROM public.activation_codes WHERE status = 'USED';
  SELECT COUNT(*) INTO v_pending_codes FROM public.activation_codes WHERE status = 'AVAILABLE';
  SELECT COUNT(*) INTO v_recent_sessions FROM public.telemetry_sessions WHERE login_at > NOW() - INTERVAL '24 hours';
  SELECT COUNT(*) INTO v_recent_errors FROM public.telemetry_errors WHERE created_at > NOW() - INTERVAL '24 hours';

  RETURN jsonb_build_object(
    'success', true,
    'stats', jsonb_build_object(
      'total_users', v_total_users,
      'active_testers', v_active_testers,
      'active_codes', v_active_codes,
      'pending_codes', v_pending_codes,
      'recent_sessions', v_recent_sessions,
      'recent_errors', v_recent_errors
    )
  );
END;
$$;

NOTIFY pgrst, 'reload schema';
